.\" Process with: man ./stress.1
.TH STRESS 1 "" "Version 4.2" "Commandes d'urgence Utilisateur"
.SH NOM
stress \- Alors euh ça sert à... enfaite à... gérer le stress ? oui voilà
.SH SYNOPSIS
.B stress
[\-h] [\-\-help] [oh non j’ai oublié les autres options]
.SH DESCRIPTION
Euh ok donc normalement ici je dois expliquer *calmement* ce que fait cette commande...  
mais j’arrive pas, parce que j’ai trop de pression, ça fait trop, vous comprenez ? J'EN PEUX PLUS.  

Bref, la commande \fBstress\fR est censée vous aider à comprendre comment le stress fonctionne... enfaite non elle doit vous permettre d'évacuer le stress 
mais honnêtement, je ne suis plus sûr de rien, et puis c'est moi qui l'ai codé donc bon.  

Bordel, pourquoi j’ai accepté d’écrire ce manuel ??  
.SH OPTIONS
.TP
.B \-h, \-\-help
Euh, ça devrait afficher de l’aide, j’espère ?  
Sinon... bah tant pis, paniquez avec moi.  

.TP
.B \-\-breath
Inspire… expire… inspire… expire… putain ça marche jamais cette merde, je panique encore.  

.TP
.B \-\-coffee
Donne un café. Ça ne résout rien mais au moins vous tremblez pour une raison valable.  

.SH EXEMPLES
.TP
.B stress \-\-help
Ça devrait être utile normalement.  
.TP
.B stress \-\-coffee \-\-breath
La combinaison la plus courante dans un open space.  

.SH AUTEUR
Rédigé dans l’urgence par atomasi et raphalme en full crise d'angoisse.  

.SH VOIR AUSSI
.BR student (1),
.BR piscineux (1),
